In [1]:
import sys
sys.path.append('..')

import pandas as pd
from utils.db_utils import write_table

In [2]:
df = pd.read_csv("../../data/Mean Salary by State.csv")

In [3]:
df_final = df.melt(
    id_vars="state",
    var_name="year",
    value_name="mean_salary_rm"
)

df_final = df_final.sort_values(["state", "year"]).reset_index(drop=True)

df_final.head()

   state  year  mean_salary_rm
0  Johor  2020          4443.0
1  Johor  2021          4514.0
2  Johor  2022          4689.0
3  Johor  2023          4855.0
4  Johor  2024          5046.3

In [4]:
write_table(df_final, 'sc_bronze', 'dosm_mean_salary_state')

postgresql+psycopg2://postgres.eaomovixhqgdatskjgdh:Lamimi123%21%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
Table sc_bronze.dosm_mean_salary_state written successfully.

In [5]:
df2 = pd.read_csv("../../data/Mean Salary by Sector.csv")

In [6]:
df2_final = df2.melt(
    id_vars="sector",
    var_name="year",
    value_name="mean_salary_rm"
)

df2_final = df2_final.sort_values(["sector", "year"]).reset_index(drop=True)

df2_final.head()

        sector  year  mean_salary_rm
0  Agriculture  2020          3264.0
1  Agriculture  2021          3325.0
2  Agriculture  2022          3359.0
3  Agriculture  2023          3435.0
4  Agriculture  2024          3526.3

In [7]:
write_table(df2_final, 'sc_bronze', 'dosm_mean_salary_sector')

postgresql+psycopg2://postgres.eaomovixhqgdatskjgdh:Lamimi123%21%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
Table sc_bronze.dosm_mean_salary_sector written successfully.