In [7]:
import sys
sys.path.append('..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [13]:
import pandas as pd

def transform_graduate_data_by_age(file_path):
    df = pd.read_csv(file_path)
    
    # 1. Reshape years into rows (Melt)
    df_long = df.melt(
        id_vars=["statistics"],
        var_name="year",
        value_name="value"
    )
    
    # 2. Extract Age Group and Category
    # Logic: If the string contains '_', split it. If not, it's a 'Total' row.
    def parse_stats(stat_name):
        if "_" in stat_name and any(char.isdigit() or char in "<>≥" for char in stat_name):
            # Handles "≤ 24_time_total", "25 - 34_skill_deg", etc.
            parts = stat_name.split("_", 1)
            return parts[0].strip(), parts[1]
        else:
            # Handles "time_total", "skill_total", etc.
            return "Total", stat_name

    # Apply the splitting logic
    df_long[['age_group', 'category']] = df_long['statistics'].apply(
        lambda x: pd.Series(parse_stats(x))
    )
    
    # 3. Pivot the categories into columns
    # Now we index by Year AND Age Group
    df_pivot = df_long.pivot_table(
        index=["year", "age_group"],
        columns="category",
        values="value",
        aggfunc="first"
    ).reset_index()
    
    # 4. Clean up formatting
    df_pivot.columns.name = None
    
    # Convert numeric columns to float
    cols_to_fix = [c for c in df_pivot.columns if c not in ["year", "age_group"]]
    for col in cols_to_fix:
        df_pivot[col] = pd.to_numeric(df_pivot[col], errors='coerce')
        
    # Optional: Sort by year and age group for readability
    df_pivot = df_pivot.sort_values(["year", "age_group"]).reset_index(drop=True)

    num_cols = [col for col in df_pivot.columns if col not in ["year", "age_group"]]

    for col in num_cols:
        df_pivot[col] = (
            df_pivot[col]
            .astype(str)
            .str.replace(",", "", regex=False)
            .astype(float) * 1000
    )
    
    return df_pivot

# df_final = transform_graduate_data_by_age("your_file.csv")

In [14]:
df_final = transform_graduate_data_by_age("../../data/underemp_stats.csv")
df_final.head(10)

,year,age_group,skill_deg,skill_dip,skill_total,time_deg,time_dip,time_total
0,2020,25 - 34,224800.0,342600.0,567400.0,14600.0,12500.0,27100.0
1,2020,35 - 44,99400.0,192200.0,291600.0,12100.0,11600.0,23700.0
2,2020,≤ 24,38700.0,160000.0,198700.0,1900.0,6100.0,8000.0
3,2020,≥ 45,53000.0,84800.0,137800.0,9200.0,5700.0,14900.0
4,2021,25 - 34,299700.0,410000.0,709600.0,16300.0,15800.0,32100.0
5,2021,35 - 44,135200.0,251500.0,386700.0,23600.0,9200.0,32700.0
6,2021,≤ 24,29400.0,144000.0,173400.0,3800.0,12300.0,16100.0
7,2021,≥ 45,55500.0,121000.0,176500.0,4700.0,3100.0,7900.0
8,2022,25 - 34,318000.0,378000.0,696000.0,19400.0,30000.0,49400.0
9,2022,35 - 44,235800.0,248500.0,484300.0,7200.0,8100.0,15300.0

In [15]:
write_table(df_final, "sc_bronze", "dosm_underemployment")
df_final.head(10)

postgresql+psycopg2://postgres.eaomovixhqgdatskjgdh:Lamimi123%21%40@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
Table sc_bronze.dosm_underemployment written successfully.

,year,age_group,skill_deg,skill_dip,skill_total,time_deg,time_dip,time_total
0,2020,25 - 34,224800.0,342600.0,567400.0,14600.0,12500.0,27100.0
1,2020,35 - 44,99400.0,192200.0,291600.0,12100.0,11600.0,23700.0
2,2020,≤ 24,38700.0,160000.0,198700.0,1900.0,6100.0,8000.0
3,2020,≥ 45,53000.0,84800.0,137800.0,9200.0,5700.0,14900.0
4,2021,25 - 34,299700.0,410000.0,709600.0,16300.0,15800.0,32100.0
5,2021,35 - 44,135200.0,251500.0,386700.0,23600.0,9200.0,32700.0
6,2021,≤ 24,29400.0,144000.0,173400.0,3800.0,12300.0,16100.0
7,2021,≥ 45,55500.0,121000.0,176500.0,4700.0,3100.0,7900.0
8,2022,25 - 34,318000.0,378000.0,696000.0,19400.0,30000.0,49400.0
9,2022,35 - 44,235800.0,248500.0,484300.0,7200.0,8100.0,15300.0