In [4]:
import sys
sys.path.append('../..')

import pandas as pd
from utils.db_utils import write_table, read_table

In [5]:
date = read_table("select * from sc_gold.dim_date")

In [6]:
df = read_table("select * from sc_bronze.dosm_olf_reason")
df

    year                    reason_not_working  total_outside_labor_force
0   2016                              Disabled                     8400.0
1   2016             Going for further studies                    15700.0
2   2016    Housework/ family responsibilities                   212500.0
3   2016  Not interested/ just completed study                    22500.0
4   2016                      Retired/ Old age                   156000.0
5   2016         Schooling/ training programme                   244500.0
6   2017                              Disabled                    12000.0
7   2017             Going for further studies                    12300.0
8   2017    Housework/ family responsibilities                   245900.0
9   2017  Not interested/ just completed study                    22900.0
10  2017                      Retired/ Old age                   200200.0
11  2017         Schooling/ training programme                   273900.0
12  2018                              Disabled                    12700.0
13  2018             Going for further studies                    17000.0
14  2018    Housework/ family responsibilities                   279000.0
15  2018  Not interested/ just completed study                    28700.0
16  2018                      Retired/ Old age                   224600.0
17  2018         Schooling/ training programme                   246500.0
18  2019                              Disabled                    12400.0
19  2019             Going for further studies                     8600.0
20  2019    Housework/ family responsibilities                   319900.0
21  2019  Not interested/ just completed study                    28400.0
22  2019                      Retired/ Old age                   260700.0
23  2019         Schooling/ training programme                   239900.0
24  2020                              Disabled                    15200.0
25  2020             Going for further studies                     9000.0
26  2020    Housework/ family responsibilities                   301000.0
27  2020  Not interested/ just completed study                     8800.0
28  2020                      Retired/ Old age                   189100.0
29  2020         Schooling/ training programme                   222700.0
30  2021                              Disabled                    39600.0
31  2021             Going for further studies                    44800.0
32  2021    Housework/ family responsibilities                   269100.0
33  2021  Not interested/ just completed study                     4800.0
34  2021                      Retired/ Old age                   189700.0
35  2021         Schooling/ training programme                   236700.0
36  2022                              Disabled                    10200.0
37  2022             Going for further studies                    19800.0
38  2022    Housework/ family responsibilities                   273600.0
39  2022  Not interested/ just completed study                    11300.0
40  2022                      Retired/ Old age                   225100.0
41  2022         Schooling/ training programme                   262900.0
42  2023                              Disabled                    14800.0
43  2023             Going for further studies                    18600.0
44  2023    Housework/ family responsibilities                   283000.0
45  2023  Not interested/ just completed study                    22500.0
46  2023                      Retired/ Old age                   230100.0
47  2023         Schooling/ training programme                   251100.0
48  2024                              Disabled                    14500.0
49  2024             Going for further studies                    22100.0
50  2024    Housework/ family responsibilities                   272300.0
51  2024  Not interested/ just completed study                     8800.0
52  2024                      Retired/ Old age                   244700.0
53  2024         Schooling/ training programme                   276300.0

In [7]:
df["date"] = pd.to_datetime(df["year"], format="%Y")
df = df.merge(
    date[["date", "date_id"]],
    on="date",
    how="left"
)

df_final = df.drop(columns=["year", "date"])
id_cols = ["date_id"]
df_final = df_final[id_cols + [col for col in df_final.columns if col not in id_cols]]

In [8]:
df_final["olf_id"] = ["OLF" + str(i+1).zfill(4) for i in range(len(df_final))]
df_final = df_final[["olf_id"] + [c for c in df_final.columns if c != "olf_id"]]
df_final

,olf_id,date_id,reason_not_working,total_outside_labor_force
0,OLF0001,DT001,Disabled,8400.0
1,OLF0002,DT001,Going for further studies,15700.0
2,OLF0003,DT001,Housework/ family responsibilities,212500.0
3,OLF0004,DT001,Not interested/ just completed study,22500.0
4,OLF0005,DT001,Retired/ Old age,156000.0
5,OLF0006,DT001,Schooling/ training programme,244500.0
6,OLF0007,DT005,Disabled,12000.0
7,OLF0008,DT005,Going for further studies,12300.0
8,OLF0009,DT005,Housework/ family responsibilities,245900.0
9,OLF0010,DT005,Not interested/ just completed study,22900.0
10,OLF0011,DT005,Retired/ Old age,200200.0
11,OLF0012,DT005,Schooling/ training programme,273900.0
12,OLF0013,DT009,Disabled,12700.0
13,OLF0014,DT009,Going for further studies,17000.0
14,OLF0015,DT009,Housework/ family responsibilities,279000.0
15,OLF0016,DT009,Not interested/ just completed study,28700.0
16,OLF0017,DT009,Retired/ Old age,224600.0
17,OLF0018,DT009,Schooling/ training programme,246500.0
18,OLF0019,DT013,Disabled,12400.0
19,OLF0020,DT013,Going for further studies,8600.0
20,OLF0021,DT013,Housework/ family responsibilities,319900.0
21,OLF0022,DT013,Not interested/ just completed study,28400.0
22,OLF0023,DT013,Retired/ Old age,260700.0
23,OLF0024,DT013,Schooling/ training programme,239900.0
24,OLF0025,DT017,Disabled,15200.0
25,OLF0026,DT017,Going for further studies,9000.0
26,OLF0027,DT017,Housework/ family responsibilities,301000.0
27,OLF0028,DT017,Not interested/ just completed study,8800.0
28,OLF0029,DT017,Retired/ Old age,189100.0
29,OLF0030,DT017,Schooling/ training programme,222700.0
30,OLF0031,DT021,Disabled,39600.0
31,OLF0032,DT021,Going for further studies,44800.0
32,OLF0033,DT021,Housework/ family responsibilities,269100.0
33,OLF0034,DT021,Not interested/ just completed study,4800.0
34,OLF0035,DT021,Retired/ Old age,189700.0
35,OLF0036,DT021,Schooling/ training programme,236700.0
36,OLF0037,DT025,Disabled,10200.0
37,OLF0038,DT025,Going for further studies,19800.0
38,OLF0039,DT025,Housework/ family responsibilities,273600.0
39,OLF0040,DT025,Not interested/ just completed study,11300.0
40,OLF0041,DT025,Retired/ Old age,225100.0
41,OLF0042,DT025,Schooling/ training programme,262900.0
42,OLF0043,DT029,Disabled,14800.0
43,OLF0044,DT029,Going for further studies,18600.0
44,OLF0045,DT029,Housework/ family responsibilities,283000.0
45,OLF0046,DT029,Not interested/ just completed study,22500.0
46,OLF0047,DT029,Retired/ Old age,230100.0
47,OLF0048,DT029,Schooling/ training programme,251100.0
48,OLF0049,DT033,Disabled,14500.0
49,OLF0050,DT033,Going for further studies,22100.0
50,OLF0051,DT033,Housework/ family responsibilities,272300.0
51,OLF0052,DT033,Not interested/ just completed study,8800.0
52,OLF0053,DT033,Retired/ Old age,244700.0
53,OLF0054,DT033,Schooling/ training programme,276300.0

In [9]:
write_table(df_final, "sc_gold", "fact_olf")

Table sc_gold.fact_olf written successfully.